apiVersion: core.openstack.org/v1beta1
kind: OpenStackControlPlane
metadata:
  name: openstack
spec:
  secret: osp-secret
  storageClass: local-storage
  keystone:
    template:
      containerImage: quay.io/tripleowallabycentos9/openstack-keystone:current-tripleo
      databaseInstance: openstack
  mariadb:
    template:
      containerImage: quay.io/tripleowallabycentos9/openstack-mariadb:current-tripleo
      storageRequest: 500M
  rabbitmq:
    template:
      replicas: 1
      #resources:
      #  requests:
      #    cpu: 500m
      #    memory: 1Gi
      #  limits:
      #    cpu: 800m
      #    memory: 1Gi
  placement:
    template:
      containerImage: quay.io/tripleowallabycentos9/openstack-placement-api:current-tripleo
  glance:
    template:
      databaseInstance: openstack
      containerImage: quay.io/tripleowallabycentos9/openstack-glance-api:current-tripleo
      storageClass: ""
      storageRequest: 10G
      glanceAPIInternal:
        containerImage: quay.io/tripleowallabycentos9/openstack-glance-api:current-tripleo
      glanceAPIExternal:
        containerImage: quay.io/tripleowallabycentos9/openstack-glance-api:current-tripleo
  cinder:
    template:
      cinderAPI:
        replicas: 1
        containerImage: quay.io/tripleowallabycentos9/openstack-cinder-api:current-tripleo
      cinderScheduler:
        replicas: 1
        containerImage: quay.io/tripleowallabycentos9/openstack-cinder-scheduler:current-tripleo
      cinderBackup:
        replicas: 1
        containerImage: quay.io/tripleowallabycentos9/openstack-cinder-backup:current-tripleo
      cinderVolumes:
        volume1:
          containerImage: quay.io/tripleowallabycentos9/openstack-cinder-volume:current-tripleo
          replicas: 1
