name: Run Renovate Bot

on:
  schedule:
    - cron:  '45 * * * *'

jobs:
  renovate:
    name: Renovatebot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v34.29.2
        with:
          configurationFile: .github/renovate-config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
